//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP423_KUZMINA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int ID_basket { get; set; }
        public int ID_product { get; set; }
        public int Count { get; set; }
        public int ID_user { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
