//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP423_KUZMINA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public int ID_box { get; set; }
        public int ID_details { get; set; }
        public int Count { get; set; }
    
        public virtual Details Details { get; set; }
    }
}
