//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP423_KUZMINA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int ID_customers { get; set; }
        public string Name { get; set; }
        public string Car_brand { get; set; }
        public int ID_problems { get; set; }
    
        public virtual Problems Problems { get; set; }
    }
}
